<?php
declare(strict_types=1);

require_once dirname(__DIR__) . '/config.php';
require_once BASE_PATH . '/src/db.php';
require_once BASE_PATH . '/src/helpers.php';
require_once BASE_PATH . '/src/auth.php';
require_once BASE_PATH . '/src/Cache.php';
require_once BASE_PATH . '/src/Notification.php';
require_once BASE_PATH . '/src/Bracket.php';
require_once BASE_PATH . '/src/Formats/FormatInterface.php';
require_once BASE_PATH . '/src/Formats/SingleElim.php';
require_once BASE_PATH . '/src/Formats/DoubleElim.php';
require_once BASE_PATH . '/src/Formats/RoundRobin.php';
require_once BASE_PATH . '/src/Formats/Swiss.php';
require_once BASE_PATH . '/src/Formats/MultiStage.php';
require_once BASE_PATH . '/src/FormatFactory.php';
require_once BASE_PATH . '/src/router.php';

session_start_once();

$uri = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);

if (str_starts_with($uri, '/api/')) {
    dispatch_api();
    exit;
}

// ---------------------------------------------------------------------------
// SPA shell — serve index.html with ETag and optional versioned asset URLs
// ---------------------------------------------------------------------------
$htmlPath = __DIR__ . '/index.html';
$mtime    = filemtime($htmlPath);
$etag     = '"' . md5((string)$mtime) . '"';

header('ETag: ' . $etag);
header('Cache-Control: no-cache'); // require revalidation, allow conditional GET

if (isset($_SERVER['HTTP_IF_NONE_MATCH']) && $_SERVER['HTTP_IF_NONE_MATCH'] === $etag) {
    http_response_code(304);
    exit;
}

header('Content-Type: text/html; charset=utf-8');

// PERF: inject versioned asset URLs from the dist manifest if available.
// Generated by: php tools/minify.php
// Falls back to the original URLs if the manifest does not exist.
$manifestPath = __DIR__ . '/assets/dist/manifest.json';
if (file_exists($manifestPath)) {
    $manifest = json_decode((string)file_get_contents($manifestPath), true) ?? [];
    $html     = (string)file_get_contents($htmlPath);
    $html     = str_replace(
        '<link rel="stylesheet" href="/assets/css/app.css">',
        '<link rel="stylesheet" href="' . htmlspecialchars($manifest['app.css'] ?? '/assets/css/app.css', ENT_QUOTES) . '">',
        $html
    );
    $html     = str_replace(
        '<script type="module" src="/assets/js/app.js"></script>',
        '<script src="' . htmlspecialchars($manifest['app.js'] ?? '/assets/js/app.js', ENT_QUOTES) . '"></script>',
        $html
    );
    echo $html;
} else {
    readfile($htmlPath);
}
